apiVersion: v1
kind: ConfigMap
metadata:
  name: execucao-config
  namespace: execucao
data:
  NODE_ENV: production
  PORT: '3000'
  JWT_ALGORITHM: RS256
  JWT_ISSUER: repo-auth-serverless
  JWT_AUDIENCE: async-furious-project
  JWT_EXPIRES_IN: '1800'
  KAFKA_BROKERS: ${kafka_brokers}
  KAFKA_CONSUMER_GROUP: execucao-service
